functions:
- envs:
  log_destinations:
  - datadog:
      api_key: fb13971f5b50fd764800c65f53b1e7b3
      endpoint: https://http-intake.logs.us3.datadoghq.com/api/v2/logs
    name: LOG_DESTINATIONS
  name: sample-functions-python-jokes
